spring.application.name=system_students




spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.dabatabase-platform=org.hibernate.dialect.PostgreSQLDialect


server.port=8080


# postgresql://neondb_owner:npg_2W4flrYoAnQL@ep-cool-bread-apkfv5ys-pooler.c-7.us-east-1.aws.neon.tech/students_db?sslmode=require&channel_binding=require

spring.datasource.url{DB_URL}
spring.datasource.username{DB_USERNAME}
spring.datasource.password{DB_PASSWORD}

#spring.datasource.driveClassName=org.postgresql.Driver